# Generated by Django 2.0.13 on 2019-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190820_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Writer',
            field=models.TextField(blank=True),
        ),
    ]
