# Generated by Django 2.0.13 on 2019-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190821_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.TextField(blank=True),
        ),
    ]
